### ISSUE TITLE
Caching without MySQL PROCESS privileges

### ISSUE THREAD

**Issue by tophcodes** [ramiusGitHub/Project-Manager#1]
Currently the `ProjectDatabaseCacheBuilder` [queries](https://github.com/ramiusGitHub/ProjectManager/blob/4273692b2b53ba4b0f3d8f020d29a9b2acb34945/wcf/lib/system/cache/builder/ProjectDatabaseCacheBuilder.class.php#L635) from `INFORMATION_SCHEMA.INNODB_SYS_FOREIGN` to retrieve foreign keys. This approach does not work when the MySQL user does not have `PROCESS` privileges, which are required to query the table.

My team is working on a shared host that does not give us the ability to grant our mysql users this privilege. Could you think of any way around this, perhaps an alternative solution in case no `PROCESS` privileges have been granted?

**Comment by ramiusGitHub** [comment]
There are ways to retrieve the information without queries to the `INFORMATION_SCHEMA`. But as far as I can tell they are not as clean and neat. The information about foreign keys have to be retrieved with string parsing.

The Project Manager is currently not designed for an usage by multiple developers. A broad support for GIT is planned, which will enable teams to work together on the same project efficiently.

The Project Manager should use a local database. Therefore you should have all privileges necessary. If you want to build an environment which differs from the designated one of the tutorial, I cannot guarantee that it will work out. But I can try to help you resolve your problems. Please consider registering on WCoding.de where you can ask questions and make feature-requests for the Project Manager in english and german.
